# -*- coding: utf-8 -*-
"""Lambda

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JkarZczCH_zQeK29r3WJURqz4inrXtRz
"""

lst = [('Dan',45),
       ('Adam',39),
       ('Fiona',42),
       ('Kathy',44),
       ('Dan',34),
       ('Adam',41),
       ('Kalin',50),
       ('Adam',40),
       ('Zehr',43),
       ('Mona',42),
       ('Kevin',35),
       ('Elma',48)]

def sortNames(i):
  if(i=='ad'):
     lst.sort(key=lambda x:(x[0]), reverse=True)
     print(lst)
  elif(i=='dd'):
     lst.sort(key=lambda x:(x[0],x[1]), reverse=False)
     print(lst)
  elif(i=='aa'):
     lst.sort(key=lambda x:(x[0],x[1]), reverse=True)
     print(lst)  
  else: print("error")



sortNames('ad')#sort in ascending order of names, if same name descending order of scores.
sortNames('dd')#sort in descending order of names, if same name descending order of scores.
sortNames('aa')#sort in ascending order of names, if same name ascending order of scores.